// Scenario list shared by test/pdf-golden.test.mjs and the one-off
// recorder. Names are stable keys into the goldens.
export const SCENARIOS = {
    'core a4 2col default':           { fixture: 'core' },
    'core a4 1col':                   { fixture: 'core', cols: 1 },
    'core letter 2col':               { fixture: 'core', paperSize: 'letter' },
    'core letter 1col':               { fixture: 'core', paperSize: 'letter', cols: 1 },
    'core 2 pages per band':          { fixture: 'core', questionsPerSet: 2 },
    'core 2 pages per band 1col':     { fixture: 'core', questionsPerSet: 2, cols: 1 },
    'core second seed group':         { fixture: 'core', count: 2, seed: 7 },
    'core large font 1.3':            { fixture: 'core', scale: 1.3 },
    'core small font 0.8':            { fixture: 'core', scale: 0.8, questionsPerSet: 2 },
    'core no key':                    { fixture: 'core', opts: { easy: true, medium: true, hard: true, key: false } },
    'core easy+key only':             { fixture: 'core', opts: { easy: true, medium: false, hard: false, key: true } },
    'core key first order':           { fixture: 'core', pageOrder: ['key', 'hard', 'medium', 'easy'] },
    'core formula sheet':             { fixture: 'core', showFormulaSheet: true },
    'core topic pills + chips':       { fixture: 'core', showTopic: true, chips: true },
    'core outcomes header':           { fixture: 'core', outcomesHeader: true, chips: true, questionsPerSet: 2 },
    'geom diagrams 2col':             { fixture: 'geom' },
    'geom diagrams 1col':             { fixture: 'geom', cols: 1 },
    'geom diagrams hidden':           { fixture: 'geom', showDiagrams: false },
    'geom 2 pages letter':            { fixture: 'geom', questionsPerSet: 2, paperSize: 'letter' },
    'geom formula sheet + key':       { fixture: 'geom', showFormulaSheet: true, questionsPerSet: 2 },
    'stats dense 2col':               { fixture: 'stats' },
    'stats 2 pages 1col':             { fixture: 'stats', questionsPerSet: 2, cols: 1 },
    'stage5 2col':                    { fixture: 'stage5' },
    'stage5 2 pages font 1.15':       { fixture: 'stage5', questionsPerSet: 2, scale: 1.15 },
    // Duplex padding (3 copies so two non-final sets can be padded)
    'duplex off 3 copies (5 pages)':    { fixture: 'core', count: 3, blankPageMode: 'off', opts: { easy: true, medium: true, hard: true, key: true } },
    'duplex odd, even set (4 pages)':   { fixture: 'core', count: 3, blankPageMode: 'odd' },
    'duplex odd, odd set (3 pages)':    { fixture: 'core', count: 3, blankPageMode: 'odd', opts: { easy: true, medium: true, hard: false, key: true } },
    'duplex always 3 copies':           { fixture: 'core', count: 3, blankPageMode: 'always' },
    'duplex always single copy':        { fixture: 'core', count: 1, blankPageMode: 'always' },
    'duplex odd with formula sheet':    { fixture: 'core', count: 2, blankPageMode: 'odd', showFormulaSheet: true },
    'duplex always 2pp letter geom':    { fixture: 'geom', count: 2, blankPageMode: 'always', questionsPerSet: 2, paperSize: 'letter' },
};
